include: package:flutter_lints/flutter.yaml

linter:
  rules:
    use_key_in_widget_constructors: true
    always_use_package_imports: true
    avoid_print: true
    always_declare_return_types: true
    depend_on_referenced_packages: false

analyzer:
  plugins:
    - dart_code_metrics
  errors:
    missing_required_param: error
    parameter_assignments: error
    missing_return: error
    todo: ignore
  exclude:
    - lib/**.config.dart
    - lib/**.gr.dart
    - lib/**.freezed.dart

dart_code_metrics:
  anti-patterns:
    - long-method:
        - severity: warning
        - exclude:
            - test/*
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    number-of-parameters: 4
    maximum-nesting-level: 5
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
    - lib/**.gr.dart
  rules:
    # dart
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
    - prefer-immediate-return
    - prefer-match-file-name:
        exclude:
          - main.dart
        severity:
          - error
    - magic-number:
        severity:
          - ignore
    - no-object-declaration
    - avoid-unused-parameters
    - prefer-async-await
    - avoid-global-state
    - avoid-throw-in-catch-block
    - avoid-non-null-assertion
    - avoid-nested-conditional-expressions
    - prefer-correct-type-name:
        min-length: 3
    # flutter
    - avoid-returning-widgets
    - avoid-wrapping-in-padding
    - prefer-const-border-radius
    - prefer-single-widget-per-file:
        ignore-private-widgets: true