class ArabicConstant {
  static Map<String, String> arabicLabels = {
    'insurance': 'تأمين',
    'contact': 'اتصال',
    'personal': 'شخصي',
    'patientDetails': 'تفاصيل المريض',
    'patientID': 'رقم المريض',
    'firstName': 'الاسم الأول',
    'middleName': 'الاسم الأوسط',
    'lastName': 'اسم العائلة',
    'suffix': 'لاحقة',
    'dateOfBirth': 'تاريخ الميلاد',
    'gender': 'جنس',
    'ssn': 'س س ن',
    'selectCountry': 'حدد الدولة',
    'selectState': 'اختر ولايه',
    'onboardingText':
        'تجربة الرعاية الصحية أعيد تصورها مع ATCare! تواصل مع أفضل الأطباء والمعالجين والمتخصصين تقريبًا.',
    'getStarted': 'البدء',
    'selectColor': 'إختر لون',
    'generalSettings': 'الاعدادات العامة',
    'settings': 'إعدادات',
    'receiveNotifications': 'تلقي الإخطارات',
    'themeDarkLight': "موضوع ضوء الظلام",
    'selectLanguage': 'اختار اللغة',
    'home': 'بيت',
    'profile': 'حساب تعريفي',
    'otherSettings': 'اعدادات اخرى',
    'changeLanguage': 'تغيير اللغة',
    'changeLocation': 'تغيير الموقع',
    'notification': 'إشعار',
    'newsletters': 'النشرات الإخبارية',
    'offersAndPromotions': 'پیشکشیں اور پروموشنز',
    'saveChanges': 'حفظ التغييرات',
    'save': 'يحفظ',
    'demographicProfile': 'ملف ديموقراطي',
    'demographic': 'السكانية',
    'healthProfile': 'الملف الصحي',
    'physicalHealth': 'الصحة الجسدية',
    'socialHealth': 'الصحة الاجتماعية',
    'mentalHealth': 'الصحة النفسية',
    'familyHealthProfile': 'ملف صحة الأسرة',
    'howAreYouFeelingToday': 'كيف تشعر اليوم؟',
    'searchDoctorOrAnything': 'ابحث عن طبيب أو أي شيء',
    'healthConditions': 'الظروف الصحية',
    'seeAll': 'اظهار الكل',
    'bloodPressure': 'ضغط الدم',
    'pulse': 'نبض',
    'perMin': 'لكل دقيقة',
    'checkup': 'فحص',
    'temp': 'درجة حرارة',
    'weight': 'وزن',
    'normal': 'طبيعي',
    'mmHg': 'mmHg',
    'oF': '°F',
    'kg': 'كلغ',
    'upcomingAppointments': 'المواعيد القادمة',
    '8Mar0920am': '8 مارس - 09:20 صباحًا',
    'videoConsultation': 'استشارة عبر الفيديو',
    'waitingForCall': 'في انتظار المكالمة',
    'audioConsultation': 'الاستشارة الصوتية',
    'drRachelBrown': 'دكتور راشيل براون',
    'diagnosticTests': 'الاختبارات التشخيصية',
    'topDoctors': 'كبار الأطباء',
    'drLouisaJackson': 'دكتورة لويزا جاكسون',
    'heartSpecialist': 'أخصائي القلب',
    'bookNow': 'احجز الآن',
    'fourPointThree': '4.3',
  };
}
