class EnglishConstant {
  static Map<String, String> englishLabels = {
    'housingAndUtilities': 'Housing & Utilities',
    'food': 'Food',
    'transportationAndChildCare': 'Transportation & Child Care',
    'educationAndEmploymentAndFinance': 'Education & Employment & Finance',
    'personalSafety': 'Personal Safety',
    'tablet': 'Tablet',
    'hrs': 'hrs',
    'every': 'Every',
    'mgPerDl': 'mg/dl',
    'anxiety': 'Anxiety',
    'depression': 'Depression',
    'mild': 'Mild',
    'moderate': 'Moderate',
    'circumference': 'Circumference',
    'waist': 'Waist',
    'head': 'Head',
    'pulseRate': 'Pulse Rate',
    'respiratory': 'Respiratory',
    'diabetic': 'Diabetic',
    'sugarFasting': 'Sugar (Fasting)',
    'sugarRandom': 'Sugar (Random)',
    'inches': 'inches',
    'bmi': 'BMI',
    'height': 'Height',
    'healthTracker': 'Health Tracker',
    'medications': 'Medications',
    'edit': 'Edit',
    'kgPerMerterSquare': 'Kg/m²',
    'merterSquare': 'm²',

    'secondaryInsurance': 'Secondary Insurance',
    'primaryInsurance': 'Primary Insurance',
    'insuranceName': 'Insurance Name',
    'healthPlan': 'Health Plan',
    'memberId': 'Member Id',
    'insuranceGroup': 'Insurance Group #',
    'endDate': 'End Date',
    'bin': 'Bin',
    'pharmacy': 'Pharmacy',
    'payerId': 'Payer Id',
    'rxBin': 'Rx Bin',
    'rxGroup': 'Rx Group',
    'rxGroupPCN': 'Rx Group PCN',
    'contactDetails': 'Contact Details',
    'cellPhoneNumber': 'Cellphone Number',
    'residenceNumber': 'Residence Number',
    'address': 'Address',
    'emergancyContactInfo': 'Emergancy Contact Info',
    'name': 'Name',
    'relation': 'Relation',
    'contactNumber': 'Contact Number',
    'yourPharmacyAddress': 'Your Pharmacy Address',
    'pharmacyName': 'Pharmacy Name',
    'city': 'City',
    'phoneNumber': 'Phone Number',
    'selectCity': 'Select City',
    'zipCode': 'Zip Code',
    'insurance': 'Insurance',
    'contact': 'Contact',
    'personal': 'Personal',
    'patientDetails': 'Patient Details',
    'patientID': 'Patient ID',
    'firstName': 'First Name',
    'middleName': 'Middle Name',
    'lastName': 'Last Name',
    'suffix': 'Suffix',
    'dateOfBirth': 'Date of Birth',
    'gender': 'Gender',
    'male': 'Male',
    'female': 'Female',
    'ssn': 'SSN',
    'selectCountry': 'Select Country',
    'selectState': 'Select State',
    'onboardingText':
        'Experience healthcare reimagined with ATCare! Connect with top doctors, therapists, and specialists virtually.',
    'getStarted': 'Get Started',
    'selectColor': "Select Colors",
    'generalSettings': 'General Settings',
    'settings': 'Settings',
    'receiveNotifications': 'Receive Notifications',
    'themeDarkLight': "Theme Dark Light",
    'selectLanguage': 'Select Language',
    'home': 'Home',
    'profile': 'Profile',
    'otherSettings': 'Other Settings',
    'changeLanguage': 'Change language',
    'changeLocation': 'Change Location',
    'notification': 'Notification',
    'newsletters': 'Newsletters',
    'offersAndPromotions': 'Offers and Promotions',
    'saveChanges': 'Save Changes',
    'save': 'Save',
    'demographicProfile': 'Demographic Profile',
    'demographic': 'Demographic',
    'healthProfile': 'Health Profile',
    'physicalHealth': 'Physical Health',
    'socialHealth': 'Social Health',
    'mentalHealth': 'Mental Health',
    'familyHealthProfile': 'Family Health Profile',
    'howAreYouFeelingToday': 'How are you feeling today?',
    'searchDoctorOrAnything': 'Search doctor or anything',
    'healthConditions': 'Health Conditions',
    'seeAll': 'See all',
    'bloodPressure': 'Blood Pressure',
    'pulse': 'Pulse',
    'perMin': 'Per min',
    'checkup': 'Checkup',
    'temp': 'Temp',
    'weight': 'Weight',
    'normal': 'Normal',
    'mmHg': 'mmHg',
    'oF': '°F',
    'kg': 'Kg',
    'upcomingAppointments': 'Upcoming Appointments',
    '8Mar0920am': '8 Mar, - 09:20 am',
    'videoConsultation': 'Video Consultation',
    'waitingForCall': 'Waiting for call',
    'audioConsultation': 'Audio Consultation',
    'drRachelBrown': 'Dr. Rachel Brown',
    'diagnosticTests': 'Diagnostic Tests',
    'topDoctors': 'Top Doctors',
    'drLouisaJackson': 'Dr. Louisa Jackson',
    'heartSpecialist': 'Heart Specialist',
    'bookNow': 'Book Now',
    'fourPointThree': '4.3',

    // signIn screen
    'account': 'Login to your Account',
    'email': 'Email Address',
    'password': 'Password',
    'forgot': 'Forgot Password?',
    'signIn': 'Sign In',
    'newAccount': 'Don’t have an account? ',
    'createAccount': 'Create Account',
  };
}
