class EnglishConstant {
  static Map<String, String> englishLabels = {
    
    'totalScore': 'Total Score',
    "theLastTwoWeeksHowOftenHaveYouBeenBotheredByAnyOfTheFollowingProblemsUseToIndicateYourAnswer":
        'the last 2 weeks, how often have you been bothered by any of the following problems? (Use “✔” to indicate your answer)',
    'feelingDownDepressedOrHopeless': 'Feeling down, depressed, or hopeless',
    'littleInterestOrPleasureInDoingThings':
        'Little interest or pleasure in doing things',
    'notAtAll': 'Not at all',
    'severalDays': 'Several Days',
    'moreThanHalfTheDays': 'More than half the days',
    'nearlyEveryDay': 'Nearly every day',
    'troubleFallingOrStayingAsleepOrSleepingTooMuch':
        'Trouble falling or staying asleep, or sleeping too much',
    'haveYouEverServedInAWarZoneOrHaveYouEverServedInANoncombatJobThatExposedYouToWarRelatedCasualties':
        'Have you ever served in a war zone, or have you ever served in a noncombat job that exposed you to war-related casualties?',
    'hasThisEverHappenedToYou': 'Has this ever happened to you?',
    'ifTheEventHappenedDidYouThinkYourLifeWasInDangerOrYouMightBeSeriouslyInjured':
        'If the event happened, did you think your life was in danger or you might be seriously injured?',
    'ifTheEventHappenedWereYouSeriouslyInjured':
        'If the event happened, were you  seriously injured?',
    'haveYouEverBeenInASeriousCarAccidentOrASeriousAccidentAtWorkOrSomewhereElse':
        'Have you ever been in a serious car accident, or a serious accident at work or somewhere else?',
    'haveYouEverBeenInAMajorNaturalOrTechnologicalDisaster':
        'Have you ever been in a major natural or technological disaster?',

    'status': 'Status',
    'noteIfYouAnswerYesForAnEventPleaseAnswerAnyAdditionalQuestionsThatAreListedIfYouAnswerNoForAnEventGoOnToTheNextEvent':
        '(Note: If you answer “Yes” for an event , please answer any additional questions that are listed, if you answer “No” for an event, go on to the next event)',
    'identified': 'Identified',
    'unidentified': 'Unidentified',
    'score': 'Score',
    'bFTQuestionnaire': 'Brief Trauma Questionnaire',
    'pHQ9': 'PHQ - 9',
    'gAD7': 'GAD - 7',
    'cageAid': 'Cage-Aid',
    'developmentDisabilityIDD': 'Development Disability (IDD)',
    'domesticViolenceChecklist': 'Domestic Violence Checklist',
    'mMSE': 'MMSE',
    'severe': 'Severe',
    'iDoNotHaveHousing': 'I do not have housing',
    'iHaveHousingTodayButIAmWorriedAboutLosingHousingInTheFuture':
        'I have housing today, but I am worried about losing housing in the future',
    'iHaveHousing': 'I have housing',
    'bugInfestation': 'Bug infestation',
    'thinkAboutThePlaceYouLiveDoYouHaveProblemsWithAnyOfTheFollowing':
        'Think about the place you live. Do you have problems with any of the following?',
    'mold': 'Mold',
    'leadPaintOrPipes': 'Lead paint or pipes',
    'inadequateHeat': 'Inadequate heat',
    'ovenOrStoveNotWorking': 'Oven or stove not working',
    'noOrNotWorkingSmokeDetectors': 'No or not working smoke detectors',
    'waterLeaks': 'Water leaks',
    'noneOfTheAbove': 'None of the above',
    'inThePastTwelveMonthsHasTheElectricGasOilOrWaterCompanyThreatenedToShutOffServicesInYourHome':
        'In the past 12 months has the electric, gas, oil, or water company threatened to shut off services in your home?',
    'yes': 'Yes',
    'no': 'No',
    'alreadyShutOff': 'Already shut off',
    'withinThePastTwelveMonthsYouWorriedThatYourFoodWouldRunOutBeforeYouGotMoneyToBuyMore':
        'Within the past 12 months, you worried that your food would run out before you got money to buy more.',
    'oftenTrue': 'Often true',
    'sometimesTrue': 'Sometimes true',
    'neverTrue': 'Never true',
    'withinThePastTwelveMonthsTheFoodYouBoughtJustDidntLastAndYouDidntHaveMoneyToGetMore':
        'Within the past 12 months, the food you bought just didn’t last and you didn’t have money to get more.',
    'inThePastTwelveMonthsHasLackOfTransportationKeptYouFromMedicalAppointmentsMeetingsWorkOrFromGettingThingsNeededForDailyLiving':
        'In the past 12 months, has lack of transportation kept you from medical appointments, meetings, work, or from getting things needed for daily living?',
    'yesItHasKeptMeFromMedicalAppointmentsOrGettingMedications':
        'Yes,it has kept me from medical appointments or getting medications',
    'yesItHasKeptMeFromNonMedicalMeetingsAppointmentsWorkOrGettingThingsThatINeed':
        'Yes, it has kept me from non-medical meetings, appointments, work, or getting things that I need',
    'doProblemsGettingChildCareMakeItDifficultForYouToWorkOrStudy':
        'Do problems getting child care make it difficult for you to work or study?',
    'doYouHaveAHighSchoolDiploma': 'Do you have a high school diploma?',
    'doYouHaveAJob': 'Do you have a job?',
    'iDontHaveEnoughMoneyToPayMyBills':
        'I don’t have enough money to pay my bills:',
    'never': 'Never',
    'rarely': 'Rarely',
    'sometimes': 'Sometimes',
    'fairlyOften': 'Fairly often',
    'frequently': 'Frequently',
    'howOftenDoesAnyoneIncludingFamilyPhysicallyHurtYou':
        'How often does anyone, including family, physically hurt you?',
    'howOftenDoesAnyoneIncludingFamilyInsultOrTalkDownToYou':
        'How often does anyone, including family, insult or talk down to you?',
    'howOftenDoesAnyoneIncludingFamilyThreatenYouWithHarm':
        'How often does anyone, including family, threaten you with harm?',
    'whatIsYourHousingSituationToday': 'What is your housing situation today?',
    'housingAndUtilities': 'Housing & Utilities',
    'food': 'Food',
    'transportationAndChildCare': 'Transportation & Child Care',
    'educationAndEmploymentAndFinance': 'Education & Employment & Finance',
    'personalSafety': 'Personal Safety',
    'tablet': 'Tablet',
    'hrs': 'hrs',
    'every': 'Every',
    'mgPerDl': 'mg/dl',
    'anxiety': 'Anxiety',
    'depression': 'Depression',
    'mild': 'Mild',
    'moderate': 'Moderate',
    'circumference': 'Circumference',
    'waist': 'Waist',
    'head': 'Head',
    'pulseRate': 'Pulse Rate',
    'respiratory': 'Respiratory',
    'diabetic': 'Diabetic',
    'sugarFasting': 'Sugar (Fasting)',
    'sugarRandom': 'Sugar (Random)',
    'inches': 'inches',
    'bmi': 'BMI',
    'height': 'Height',
    'healthTracker': 'Health Tracker',
    'medications': 'Medications',
    'edit': 'Edit',
    'kgPerMerterSquare': 'Kg/m²',
    'merterSquare': 'm²',

    'secondaryInsurance': 'Secondary Insurance',
    'primaryInsurance': 'Primary Insurance',
    'insuranceName': 'Insurance Name',
    'healthPlan': 'Health Plan',
    'memberId': 'Member Id',
    'insuranceGroup': 'Insurance Group #',
    'endDate': 'End Date',
    'bin': 'Bin',
    'pharmacy': 'Pharmacy',
    'payerId': 'Payer Id',
    'rxBin': 'Rx Bin',
    'rxGroup': 'Rx Group',
    'rxGroupPCN': 'Rx Group PCN',
    'contactDetails': 'Contact Details',
    'cellPhoneNumber': 'Cellphone Number',
    'residenceNumber': 'Residence Number',
    'address': 'Address',
    'emergancyContactInfo': 'Emergancy Contact Info',
    'name': 'Name',
    'relation': 'Relation',
    'contactNumber': 'Contact Number',
    'yourPharmacyAddress': 'Your Pharmacy Address',
    'pharmacyName': 'Pharmacy Name',
    'city': 'City',
    'phoneNumber': 'Phone Number',
    'selectCity': 'Select City',
    'zipCode': 'Zip Code',
    'insurance': 'Insurance',
    'contact': 'Contact',
    'personal': 'Personal',
    'patientDetails': 'Patient Details',
    'patientID': 'Patient ID',
    'firstName': 'First Name',
    'middleName': 'Middle Name',
    'lastName': 'Last Name',
    'suffix': 'Suffix',
    'dateOfBirth': 'Date of Birth',
    'gender': 'Gender',
    'male': 'Male',
    'female': 'Female',
    'ssn': 'SSN',
    'selectCountry': 'Select Country',
    'selectState': 'Select State',
    'onboardingText':
        'Experience healthcare reimagined with ATCare! Connect with top doctors, therapists, and specialists virtually.',
    'getStarted': 'Get Started',
    'selectColor': "Select Colors",
    'generalSettings': 'General Settings',
    'settings': 'Settings',
    'receiveNotifications': 'Receive Notifications',
    'themeDarkLight': "Theme Dark Light",
    'selectLanguage': 'Select Language',
    'home': 'Home',
    'profile': 'Profile',
    'otherSettings': 'Other Settings',
    'changeLanguage': 'Change language',
    'changeLocation': 'Change Location',
    'notification': 'Notification',
    'newsletters': 'Newsletters',
    'offersAndPromotions': 'Offers and Promotions',
    'saveChanges': 'Save Changes',
    'save': 'Save',
    'demographicProfile': 'Demographic Profile',
    'demographic': 'Demographic',
    'healthProfile': 'Health Profile',
    'physicalHealth': 'Physical Health',
    'socialHealth': 'Social Health',
    'mentalHealth': 'Mental Health',
    'familyHealthProfile': 'Family Health Profile',
    'howAreYouFeelingToday': 'How are you feeling today?',
    'searchDoctorOrAnything': 'Search doctor or anything',
    'healthConditions': 'Health Conditions',
    'seeAll': 'See all',
    'bloodPressure': 'Blood Pressure',
    'pulse': 'Pulse',
    'perMin': 'Per min',
    'checkup': 'Checkup',
    'temp': 'Temp',
    'weight': 'Weight',
    'normal': 'Normal',
    'mmHg': 'mmHg',
    'oF': '°F',
    'kg': 'Kg',
    'upcomingAppointments': 'Upcoming Appointments',
    '8Mar0920am': '8 Mar, - 09:20 am',
    'videoConsultation': 'Video Consultation',
    'waitingForCall': 'Waiting for call',
    'audioConsultation': 'Audio Consultation',
    'drRachelBrown': 'Dr. Rachel Brown',
    'diagnosticTests': 'Diagnostic Tests',
    'topDoctors': 'Top Doctors',
    'drLouisaJackson': 'Dr. Louisa Jackson',
    'heartSpecialist': 'Heart Specialist',
    'bookNow': 'Book Now',
    'fourPointThree': '4.3',

    // signIn screen
    'account': 'Login to your Account',
    'email': 'Email Address',
    'password': 'Password',
    'forgot': 'Forgot Password?',
    'signIn': 'Sign In',
    'newAccount': 'Don’t have an account? ',
    'createAccount': 'Create Account',
  };
}
