class EnglishConstant {
  static Map<String, String> englishLabels = {
    'onboardingText':
        'Experience healthcare reimagined with ATCare! Connect with top doctors, therapists, and specialists virtually.',
    'getStarted': 'Get Started',
    'selectColor': "Select Colors",
    'generalSettings': 'General Settings',
    'settings': 'Settings',
    'receiveNotifications': 'Receive Notifications',
    'themeDarkLight': "Theme Dark Light",
    'selectLanguage': 'Select Language',
    'home': 'Home',
    'profile': 'Profile',
    'otherSettings': 'Other Settings',
    'changeLanguage': 'Change language',
    'changeLocation': 'Change Location',
    'notification': 'Notification',
    'newsletters': 'Newsletters',
    'offersAndPromotions': 'Offers and Promotions',
    'saveChanges': 'Save Changes',
    'demographicProfile': 'Demographic Profile',
    'healthProfile': 'Health Profile',
    'physicalHealth': 'Physical Health',
    'socialHealth': 'Social Health',
    'mentalHealth': 'Mental Health',
    'familyHealthProfile': 'Family Health Profile',
    'howAreYouFeelingToday': 'How are you feeling today?',
    'searchDoctorOrAnything': 'Search doctor or anything',
    'healthConditions': 'Health Conditions',
    'seeAll': 'See all',
    'bloodPressure': 'Blood Pressure',
    'pulse': 'Pulse',
    'perMin': 'Per min',
    'checkup': 'Checkup',
    'temp': 'Temp',
    'weight': 'Weight',
    'normal': 'Normal',
    'mmHg': 'mmHg',
    'oF': '°F',
    'kg': 'Kg',
    'upcomingAppointments': 'Upcoming Appointments',
    '8Mar0920am': '8 Mar, - 09:20 am',
    'videoConsultation': 'Video Consultation',
    'waitingForCall': 'Waiting for call',
    'audioConsultation': 'Audio Consultation',
    'drRachelBrown': 'Dr. Rachel Brown',
    'diagnosticTests': 'Diagnostic Tests',
    'topDoctors': 'Top Doctors',
    'drLouisaJackson': 'Dr. Louisa Jackson',
    'heartSpecialist': 'Heart Specialist',
    'bookNow': 'Book Now',
    'fourPointThree':'4.3',
  };
}
