class HindiConstant {
  static Map<String, String> hindiLabels = {
    'onboardingText':
        'ATCare के साथ पुनर्कल्पित स्वास्थ्य सेवा का अनुभव लें! शीर्ष डॉक्टरों, चिकित्सकों और विशेषज्ञों से वर्चुअली जुड़ें।',
    'getStarted': 'बहुत बढ़िया',
    'selectColor': 'रंग चुनो',
    'generalSettings': 'सामान्य सेटिंग्स',
    'settings': 'समायोजन',
    'receiveNotifications': 'सूचनाएं प्राप्त करें',
    'themeDarkLight': "थीम डार्क लाइट",
    'selectLanguage': 'भाषा चुने',
    'home': 'घर',
    'profile': 'प्रोफ़ाइल',
    'otherSettings': 'अन्य सेटिंग',
    'changeLanguage': 'भाषा बदलें',
    'changeLocation': 'स्थान बदलें',
    'notification': 'अधिसूचना',
    'newsletters': 'समाचार',
    'offersAndPromotions': 'ऑफर और प्रमोशन',
    'saveChanges': 'परिवर्तनों को सुरक्षित करें',
    'save': 'बचाना',
    'demographicProfile': 'जनसांख्यिकीय प्रोफाइल',
    'demographic': 'السكانية',
    'healthProfile': 'स्वास्थ्य प्रोफ़ाइल',
    'physicalHealth': 'शारीरिक मौत',
    'socialHealth': 'सामाजिक स्वास्थ्य',
    'mentalHealth': 'मानसिक स्वास्थ्य',
    'familyHealthProfile': 'पारिवारिक स्वास्थ्य प्रोफ़ाइल',
    'howAreYouFeelingToday': 'आज आप कैसा महसूस कर रहे हैं?',
    'searchDoctorOrAnything': 'डॉक्टर या कुछ भी खोजें',
    'healthConditions': 'स्वास्थ्य की स्थिति',
    'seeAll': 'सभी देखें',
    'bloodPressure': 'रक्तचाप',
    'pulse': 'नाड़ी',
    'perMin': 'प्रति मिनट',
    'checkup': 'जांच',
    'temp': 'अस्थायी',
    'weight': 'वज़न',
    'normal': 'सामान्य',
    'mmHg': 'mmHg',
    'oF': '°F',
    'kg': 'Kg',
    'upcomingAppointments': 'आगामी नियुक्तियाँ',
    '8Mar0920am': '8 मार्च, - सुबह 09:20 बजे',
    'videoConsultation': 'वीडियो परामर्श',
    'waitingForCall': 'कॉल का इंतजार है',
    'audioConsultation': 'ऑडियो परामर्श',
    'drRachelBrown': 'डॉ. राचेल ब्राउन',
    'diagnosticTests': 'नैदानिक ​​परीक्षण',
    'topDoctors': 'शीर्ष डॉक्टर',
    'drLouisaJackson': 'डॉ लुईसा जैक्सन',
    'heartSpecialist': 'हृदय रोग विशेषज्ञ',
    'bookNow': 'अभी बुक करें',
    'fourPointThree': '4.3',
  };
}
