class SpanishConstant {
  static Map<String, String> spanishLabels = {
    'onboardingText':
        '¡Experimente la atención médica reinventada con ATCare! Conéctese virtualmente con los mejores médicos, terapeutas y especialistas.',
    'getStarted': 'Empezar',
    'selectColor': 'seleccionar el color',
    'generalSettings': 'Configuración general',
    'settings': 'Ajustes',
    'receiveNotifications': 'Recibir notificaciones',
    'themeDarkLight': "Tema Luz Oscura",
    'selectLanguage': 'Seleccione el idioma',
    'home': 'Hogar',
    'profile': 'Perfil',
    'otherSettings': 'Otros ajustes',
    'changeLanguage': 'Cambiar idioma',
    'changeLocation': 'Cambiar locación',
    'notification': 'notificación',
    'newsletters': 'Boletines',
    'offersAndPromotions': 'ofertas y promociones',
    'saveChanges': 'Guardar cambios',
    'demographicProfile': 'Perfil demográfico',
    'healthProfile': 'Perfil de salud',
    'physicalHealth': 'Salud física',
    'socialHealth': 'Salud social',
    'mentalHealth': 'Salud mental',
    'familyHealthProfile': 'Perfil de salud familiar',
    'howAreYouFeelingToday': '¿Cómo te sientes hoy?',
    'searchDoctorOrAnything': 'Buscar doctor o cualquier cosa',
    'healthConditions': 'Condiciones de salud',
    'seeAll': 'Ver todo',
    'bloodPressure': 'Presión arterial',
    'pulse': 'Legumbres',
    'perMin': 'Por minuto',
    'checkup': 'Chequeo',
    'temp': 'Temperatura',
    'weight': 'Peso',
    'normal': 'Normal',
    'mmHg': 'mmHg',
    'oF': '°F',
    'kg': 'Kg',
    'upcomingAppointments': 'Próximas citas',
    '8Mar0920am': '8 marzo, - 09:20 am',
    'videoConsultation': 'Videoconsulta',
    'waitingForCall': 'esperando llamada',
    'audioConsultation': 'Consulta de audio',
    'drRachelBrown': 'Dra. Raquel Brown',
    'diagnosticTests': 'Pruebas de diagnóstico',
    'topDoctors': 'Mejores Doctores',
    'drLouisaJackson': 'Dra. Louisa Jackson',
    'heartSpecialist': 'Especialista en corazón',
    'bookNow': 'Reservar ahora',
    'fourPointThree': '4.3',
  };
}
