class UrduConstant {
  static Map<String, String> urduLabels = {
    'onboardingText':
        'اے ٹی کیئر کے ساتھ صحت کی دیکھ بھال کا دوبارہ تصور کریں! اعلیٰ ڈاکٹروں، معالجین اور ماہرین سے عملی طور پر جڑیں۔',
    'getStarted': 'شروع کریں',
    'selectColor': 'رنگ منتخب کریں',
    'generalSettings': 'عام ترتیبات',
    'settings': 'ترتیبات',
    'receiveNotifications': 'اطلاعات موصول کریں۔',
    'themeDarkLight': "تھیم ڈارک لائٹ",
    'selectLanguage': 'زبان منتخب کریں۔',
    'home': 'گھر',
    'profile': 'پروفائل',
    'otherSettings': 'دیگر ترتیبات',
    'changeLanguage': 'زبان تبدیل کریں',
    'changeLocation': 'مقام تبدیل کریں۔',
    'notification': 'اطلاع',
    'newsletters': 'خبرنامے',
    'offersAndPromotions': 'پیشکشیں اور پروموشنز',
    'saveChanges': 'تبدیلیاں محفوظ کرو',
    'demographicProfile': 'ڈیموگرافک پروفائل',
    'healthProfile': 'ہیلتھ پروفائل',
    'physicalHealth': 'جسمانی صحت',
    'socialHealth': 'سماجی صحت',
    'mentalHealth': 'دماغی صحت',
    'familyHealthProfile': 'فیملی ہیلتھ پروفائل',
    'howAreYouFeelingToday': 'آج آپ کیسا محسوس کر رہے ہیں؟',
    'searchDoctorOrAnything': 'ڈاکٹر یا کچھ بھی تلاش کریں۔',
    'healthConditions': 'صحت کے حالات',
    'seeAll': 'تمام دیکھیں',
    'bloodPressure': 'بلڈ پریشر',
    'pulse': 'نبض',
    'perMin': 'فی منٹ',
    'checkup': 'جانچ پڑتال',
    'temp': 'درجہ حرارت',
    'weight': 'وزن',
    'normal': 'نارمل',
    'mmHg': 'mmHg',
    'oF': '°F',
    'kg': 'کلو',
    'upcomingAppointments': 'آنے والی ملاقاتیں',
    '8Mar0920am': '8 مارچ، صبح 09:20 بجے',
    'videoConsultation': 'ویڈیو مشاورت',
    'waitingForCall': 'کال کا انتظار کر رہے ہیں۔',
    'audioConsultation': 'آڈیو مشاورت',
    'drRachelBrown': 'ڈاکٹر ریچل براؤن',
    'diagnosticTests': 'تشخیصی ٹیسٹ',
    'topDoctors': 'ٹاپ ڈاکٹرز',
    'drLouisaJackson': 'ڈاکٹر لوئیسا جیکسن',
    'heartSpecialist': 'ماہر امراض قلب',
    'bookNow': 'ابھی بک کریں۔',
    'fourPointThree': '4.3',
  };
}
