class UrduConstant {
  static Map<String, String> urduLabels = {
    'contactDetails': 'Contact Details',
    'cellPhoneNumber': 'Cellphone Number',
    'residenceNumber': 'Residence Number',
    'address': 'Address',
    'emergancyContactInfo': 'Emergancy Contact Info',
    'name': 'Name',
    'relation': 'Relation',
    'contactNumber': 'Contact Number',
    'yourPharmacyAddress': 'Your Pharmacy Address',
    'pharmacyName': 'Pharmacy Name',
    'city': 'City',
    'phoneNumber': 'Phone Number',
    'selectCity': 'شہر منتخب کریں۔',
    'zipCode': 'زپ کوڈ',
    'insurance': 'انشورنس',
    'contact': 'رابطہ کریں۔',
    'personal': 'ذاتی',
    'patientDetails': 'مریض کی تفصیلات',
    'patientID': 'مریض کی شناخت',
    'firstName': 'پہلا نام',
    'middleName': 'درمیانی نام',
    'lastName': 'آخری نام',
    'suffix': 'لاحقہ',
    'dateOfBirth': 'پیدائش کی تاریخ',
    'gender': 'صنف',
    'ssn': 'ایس ایس این',
    'selectCountry': 'ملک کا انتخاب کیجئے',
    'selectState': 'ریاست منتخب کریں۔',
    'onboardingText':
        'اے ٹی کیئر کے ساتھ صحت کی دیکھ بھال کا دوبارہ تصور کریں! اعلیٰ ڈاکٹروں، معالجین اور ماہرین سے عملی طور پر جڑیں۔',
    'getStarted': 'شروع کریں',
    'selectColor': 'رنگ منتخب کریں',
    'generalSettings': 'عام ترتیبات',
    'settings': 'ترتیبات',
    'receiveNotifications': 'اطلاعات موصول کریں۔',
    'themeDarkLight': "تھیم ڈارک لائٹ",
    'selectLanguage': 'زبان منتخب کریں۔',
    'home': 'گھر',
    'profile': 'پروفائل',
    'otherSettings': 'دیگر ترتیبات',
    'changeLanguage': 'زبان تبدیل کریں',
    'changeLocation': 'مقام تبدیل کریں۔',
    'notification': 'اطلاع',
    'newsletters': 'خبرنامے',
    'offersAndPromotions': 'پیشکشیں اور پروموشنز',
    'saveChanges': 'تبدیلیاں محفوظ کرو',
    'save': 'محفوظ کریں۔',
    'demographicProfile': 'ڈیموگرافک پروفائل',
    'demographic': 'آبادیاتی',
    'healthProfile': 'ہیلتھ پروفائل',
    'physicalHealth': 'جسمانی صحت',
    'socialHealth': 'سماجی صحت',
    'mentalHealth': 'دماغی صحت',
    'familyHealthProfile': 'فیملی ہیلتھ پروفائل',
    'howAreYouFeelingToday': 'آج آپ کیسا محسوس کر رہے ہیں؟',
    'searchDoctorOrAnything': 'ڈاکٹر یا کچھ بھی تلاش کریں۔',
    'healthConditions': 'صحت کے حالات',
    'seeAll': 'تمام دیکھیں',
    'bloodPressure': 'بلڈ پریشر',
    'pulse': 'نبض',
    'perMin': 'فی منٹ',
    'checkup': 'جانچ پڑتال',
    'temp': 'درجہ حرارت',
    'weight': 'وزن',
    'normal': 'نارمل',
    'mmHg': 'mmHg',
    'oF': '°F',
    'kg': 'کلو',
    'upcomingAppointments': 'آنے والی ملاقاتیں',
    '8Mar0920am': '8 مارچ، صبح 09:20 بجے',
    'videoConsultation': 'ویڈیو مشاورت',
    'waitingForCall': 'کال کا انتظار کر رہے ہیں۔',
    'audioConsultation': 'آڈیو مشاورت',
    'drRachelBrown': 'ڈاکٹر ریچل براؤن',
    'diagnosticTests': 'تشخیصی ٹیسٹ',
    'topDoctors': 'ٹاپ ڈاکٹرز',
    'drLouisaJackson': 'ڈاکٹر لوئیسا جیکسن',
    'heartSpecialist': 'ماہر امراض قلب',
    'bookNow': 'ابھی بک کریں۔',
    'fourPointThree': '4.3',
  };
}
