import 'package:softtech_test/src/pages/family_health_profile/family_health_inner_pages/health_profile/model/disease_family_members.dart';
import 'package:softtech_test/src/pages/family_health_profile/family_health_inner_pages/health_profile/model/family_members.dart';

List<DiseaseFamilyMembers> diseases = [
  DiseaseFamilyMembers(diseaseTitle: 'Alcohol Abuse', familyMembers: [
    FamilyMember(name: 'Mother', isSelected: false),
    FamilyMember(name: 'Father', isSelected: false),
    FamilyMember(name: 'Sister', isSelected: false),
    FamilyMember(name: 'Brother', isSelected: false),
    FamilyMember(name: 'Daughter', isSelected: false),
    FamilyMember(name: 'Son', isSelected: false),
    FamilyMember(name: 'Other', isSelected: false),
  ]),
  DiseaseFamilyMembers(diseaseTitle: 'Asthma', familyMembers: [
    FamilyMember(name: 'Mother', isSelected: false),
    FamilyMember(name: 'Father', isSelected: false),
    FamilyMember(name: 'Sister', isSelected: false),
    FamilyMember(name: 'Brother', isSelected: false),
    FamilyMember(name: 'Daughter', isSelected: false),
    FamilyMember(name: 'Son', isSelected: false),
    FamilyMember(name: 'Other', isSelected: false),
  ]),
  DiseaseFamilyMembers(diseaseTitle: 'Autoimmune Disease', familyMembers: [
    FamilyMember(name: 'Mother', isSelected: false),
    FamilyMember(name: 'Father', isSelected: false),
    FamilyMember(name: 'Sister', isSelected: false),
    FamilyMember(name: 'Brother', isSelected: false),
    FamilyMember(name: 'Daughter', isSelected: false),
    FamilyMember(name: 'Son', isSelected: false),
    FamilyMember(name: 'Other', isSelected: false),
  ]),
  DiseaseFamilyMembers(diseaseTitle: 'Birth Defects', familyMembers: [
    FamilyMember(name: 'Mother', isSelected: false),
    FamilyMember(name: 'Father', isSelected: false),
    FamilyMember(name: 'Sister', isSelected: false),
    FamilyMember(name: 'Brother', isSelected: false),
    FamilyMember(name: 'Daughter', isSelected: false),
    FamilyMember(name: 'Son', isSelected: false),
    FamilyMember(name: 'Other', isSelected: false),
  ]),
  DiseaseFamilyMembers(diseaseTitle: 'Cancer', familyMembers: [
    FamilyMember(name: 'Mother', isSelected: false),
    FamilyMember(name: 'Father', isSelected: false),
    FamilyMember(name: 'Sister', isSelected: false),
    FamilyMember(name: 'Brother', isSelected: false),
    FamilyMember(name: 'Daughter', isSelected: false),
    FamilyMember(name: 'Son', isSelected: false),
    FamilyMember(name: 'Other', isSelected: false),
  ]),
  DiseaseFamilyMembers(diseaseTitle: 'Cardiac Disease', familyMembers: [
    FamilyMember(name: 'Mother', isSelected: false),
    FamilyMember(name: 'Father', isSelected: false),
    FamilyMember(name: 'Sister', isSelected: false),
    FamilyMember(name: 'Brother', isSelected: false),
    FamilyMember(name: 'Daughter', isSelected: false),
    FamilyMember(name: 'Son', isSelected: false),
    FamilyMember(name: 'Other', isSelected: false),
  ]),
  DiseaseFamilyMembers(diseaseTitle: 'Dementia', familyMembers: [
    FamilyMember(name: 'Mother', isSelected: false),
    FamilyMember(name: 'Father', isSelected: false),
    FamilyMember(name: 'Sister', isSelected: false),
    FamilyMember(name: 'Brother', isSelected: false),
    FamilyMember(name: 'Daughter', isSelected: false),
    FamilyMember(name: 'Son', isSelected: false),
    FamilyMember(name: 'Other', isSelected: false),
  ]),
  DiseaseFamilyMembers(diseaseTitle: 'Despression', familyMembers: [
    FamilyMember(name: 'Mother', isSelected: false),
    FamilyMember(name: 'Father', isSelected: false),
    FamilyMember(name: 'Sister', isSelected: false),
    FamilyMember(name: 'Brother', isSelected: false),
    FamilyMember(name: 'Daughter', isSelected: false),
    FamilyMember(name: 'Son', isSelected: false),
    FamilyMember(name: 'Other', isSelected: false),
  ]),
  DiseaseFamilyMembers(diseaseTitle: 'Diabetes', familyMembers: [
    FamilyMember(name: 'Mother', isSelected: false),
    FamilyMember(name: 'Father', isSelected: false),
    FamilyMember(name: 'Sister', isSelected: false),
    FamilyMember(name: 'Brother', isSelected: false),
    FamilyMember(name: 'Daughter', isSelected: false),
    FamilyMember(name: 'Son', isSelected: false),
    FamilyMember(name: 'Other', isSelected: false),
  ]),
  DiseaseFamilyMembers(diseaseTitle: 'Hypertension', familyMembers: [
    FamilyMember(name: 'Mother', isSelected: false),
    FamilyMember(name: 'Father', isSelected: false),
    FamilyMember(name: 'Sister', isSelected: false),
    FamilyMember(name: 'Brother', isSelected: false),
    FamilyMember(name: 'Daughter', isSelected: false),
    FamilyMember(name: 'Son', isSelected: false),
    FamilyMember(name: 'Other', isSelected: false),
  ]),
  DiseaseFamilyMembers(diseaseTitle: 'Kidney Disease', familyMembers: [
    FamilyMember(name: 'Mother', isSelected: false),
    FamilyMember(name: 'Father', isSelected: false),
    FamilyMember(name: 'Sister', isSelected: false),
    FamilyMember(name: 'Brother', isSelected: false),
    FamilyMember(name: 'Daughter', isSelected: false),
    FamilyMember(name: 'Son', isSelected: false),
    FamilyMember(name: 'Other', isSelected: false),
  ]),
  DiseaseFamilyMembers(diseaseTitle: 'Mental illness', familyMembers: [
    FamilyMember(name: 'Mother', isSelected: false),
    FamilyMember(name: 'Father', isSelected: false),
    FamilyMember(name: 'Sister', isSelected: false),
    FamilyMember(name: 'Brother', isSelected: false),
    FamilyMember(name: 'Daughter', isSelected: false),
    FamilyMember(name: 'Son', isSelected: false),
    FamilyMember(name: 'Other', isSelected: false),
  ]),
  DiseaseFamilyMembers(diseaseTitle: 'Respiratory Disease', familyMembers: [
    FamilyMember(name: 'Mother', isSelected: false),
    FamilyMember(name: 'Father', isSelected: false),
    FamilyMember(name: 'Sister', isSelected: false),
    FamilyMember(name: 'Brother', isSelected: false),
    FamilyMember(name: 'Daughter', isSelected: false),
    FamilyMember(name: 'Son', isSelected: false),
    FamilyMember(name: 'Other', isSelected: false),
  ]),
  DiseaseFamilyMembers(diseaseTitle: 'Stroke', familyMembers: [
    FamilyMember(name: 'Mother', isSelected: false),
    FamilyMember(name: 'Father', isSelected: false),
    FamilyMember(name: 'Sister', isSelected: false),
    FamilyMember(name: 'Brother', isSelected: false),
    FamilyMember(name: 'Daughter', isSelected: false),
    FamilyMember(name: 'Son', isSelected: false),
    FamilyMember(name: 'Other', isSelected: false),
  ]),
  DiseaseFamilyMembers(diseaseTitle: 'Smoking Habit', familyMembers: [
    FamilyMember(name: 'Mother', isSelected: false),
    FamilyMember(name: 'Father', isSelected: false),
    FamilyMember(name: 'Sister', isSelected: false),
    FamilyMember(name: 'Brother', isSelected: false),
    FamilyMember(name: 'Daughter', isSelected: false),
    FamilyMember(name: 'Son', isSelected: false),
    FamilyMember(name: 'Other', isSelected: false),
  ]),
];
